### PR TITLE
create symlinks in multiple node_modules directories

### PR DESCRIPTION
**Pull request by iamdavidmartin**
HI there,

This plugin is super handy - thanks for making it!

When using lambda layers it is necessary to run `npm install` on > 1 directory, once for each lambda layer. When this requirement is combined with yarn workspaces and a serverless deployment, then the `serverless-plugin-monorepo` should create symlinks in all lambda layer directories.

Currently this plugin only runs in a single directory, by default the current working directory. However, I need it to run in subdirectories where the lambda layers are stored as well because they also take advantage of yarn workspaces.

So I've modified this plugin so it can accept an array of paths in the `custom` section of serverless.yml, then iterate through those and run the installation in all the directories I need.

I've made sure it remains backwards compatible with previous `custom` configurations, so it detects whether the params are an array or not and sets itself up appropriately. Though undocumented, the plugin did accept `path` and `linkType` as params. Existing installations should remain unaffected.

Ok, that's all for now. Hope you like it and others find it useful.

### CODE REVIEW

**Comment by iamdavidmartin** [comment]
Please wait it looks like there may be a deployment issue. Investigating...

**Comment by iamdavidmartin** [comment]
Some additional changes:

The `path` variable that was undocumented but accepted only accepted fully qualified path names, but it needs to be relative to the serverless.yml location. I updated the code for it to be relative.

The package.json has its `main` entry point as 'lib/index.js` which is also the `outDir` for the TypeScript. However, in your `.gitignore` you ignore that `lib` directory. So, node will never find that `lib/index.js` file, and it reverts to an `index.js` that's at the root level of the project.

I think this is a mistake. I removed the root level `index.js` and I also removed `lib` from `.gitignore` so that the `package.json` points to the correct `lib/index.js`.

I think it's looking pretty good. Let me know what you think.

**Comment by iamdavidmartin** [comment]
I've come across an issue that's prevented me from using this plugin any further. Basically, if I have `package-a` as a dependency in my `package.json`, the symlink will be created for `package-a`. However, `package-a` also has a `package.json` that has `package-b` as a dependency. In this instance, `package-b` is not added as a symlink and the code fails because `package-b` cannot be found.

So in the meantime I reverted back to using `nohoist` in my monorepo and having all libraries copied instead of using this plugin. Does this sound like an issue you're familiar with?

**Comment by martin-css** [comment]
Thanks for the PR. I think supporting multiple lambda layers is probably worthwhile but I'd like to tidy up the plugin a bit first before making a larger change like this.

> The package.json has its main entry point as lib/index.js which is also the outDir for the TypeScript. However, in your .gitignore you ignore that lib directory. So, node will never find that lib/index.js file, and it reverts to an index.js that's at the root level of the project which seems to be an old version of the pre-typescript implementation.
>
> I think this is a mistake. I removed the root level index.js and I also removed lib from .gitignore so that the package.json points to the correct lib/index.js.

You're correct, the root level `index.js` was the old code prior to conversion to Typescript and should have been removed. This was a silly oversight and has now been fixed.

The `.gitignore` file doesn't need changed, this is deliberate to prevent built code from polluting the repo. Node doesn't care about Git exclusions and will find the file just fine. The built code is included in the published NPM package.

**Comment by iamdavidmartin** [comment]
thanks for the reply.

i've moved on from the serverless framework to serverless stack: https://github.com/serverless-stack/serverless-stack

in my opinion, it's a major improvement. worth checking out.

**Pull request closed without merging**
